### ISSUE TITLE
Problemas con el git

### ISSUE THREAD

**Issue by angeltorrado** [LSLSpanish/translation_GPLv3_to_spanish#30]
Hola chicos,

   estaba mirando las gráficas que ofrece github y no sé si os habéis dado cuenta, pero actualmente aparece como que mi usuario no se corresponde con ninguna modificación anterior... Como me ha mosqueado, he estado mirando el histórico y he podido comprobar que lo mismo ocurre con Gonzalo y algunos puntuales de Héctor. Aparecen nuestros nombres, pero no están asociados a nuestra cuenta.

   Alguna idea de por qué puede ocurrir esto y cómo arreglarlo!? =(

**Comment by bmenendez** [comment]
Cierro este issue, ya se arregló todo en su momento.
