### ISSUE TITLE
LGPL y AGPL

### ISSUE THREAD

**Issue by hjmacho** [LSLSpanish/translation_GPLv3_to_spanish#31]
Me ha hecho ilusión el hecho de que nuestra traducción aparezca en la página de GNU y me estoy planteando traducir la LGPL y la AGPL (ya no como práctica de la asignatura ya que no daría tiempo a terminarla antes del examen). 
¿Alguien se anima?

Héctor.

**Comment by bmenendez** [comment]
Cierro este issue, porque aunque no se arregló, en caso de seguir con la idea podríamos abrir otro nuevo (o, simplemente, empezar la tarea cuando queramos :-) )
